[[redirects]]
  from = "/*"
  to = "https://kailistacey.com/:splat"
  status = 301
  conditions = {Host = ["kailistutoring.netlify.app"]}

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  buildDir = "dist"
  changefreq = { "/" = "monthly" }
  priority = { "/" = 1 }
  
