[[redirects]]
  from = "/"
  to = "https://kailistacey.com/"
  status = 301
  conditions = {Host = ["kailistutoring.netlify.app"]}

[[redirects]]
  from = "/*"
  to = "https://kailistacey.com/:splat"
  status = 301
  conditions = {Host = ["kailistutoring.netlify.app"]}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "dist"
  
  [plugins.inputs.changeFrequencies]
  "/" = "monthly"
  
  [plugins.inputs.priorities]
  "/" = 1.0