[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

  from = "https://kailistutoring.netlify.app/*"
  to = "https://kailistacey.com/:splat"
  status = 301

[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "dist"
  
  [plugins.inputs.changeFrequencies]
  "/" = "monthly"
  
  [plugins.inputs.priorities]
  "/" = 1.0